# Generated by Django 4.2.3 on 2023-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
