# Generated by Django 4.2.3 on 2023-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventcategory_code_alter_eventcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
