# Generated by Django 4.2.3 on 2023-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_count',
            field=models.PositiveIntegerField(),
        ),
    ]
